voting_categories:
  type: list
  list_type: category
  default: ""
  description: 
    en: 'The above categories will have the styling applied'
vote_from_topic_list:
  type: bool
  default: false
  description:
    en: '(EXPERIMENTAL) Allow users to vote from the topic list of a voting category. Excerpts are automatically enabled'
